name: NPM Publish and Trigger Downstream

on:
  push:
    branches:
      - develop

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Configure Git
        run: |
          git config --global user.email "Prashanthmsktm@gmail.com"
          git config --global user.name "prashanthNair "

      - name: Bump Version
        run: npm version patch -m "Bump version to %s"

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  trigger-downstream:
    needs: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Downstream Repository
        uses: actions/checkout@v3
        with:
          repository: hcl-x/hep-authoring-ui
          ref: mavericks_dev

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update Package Version in Downstream Repository
        run: |
          # Extract the latest version from the NPM registry
          LATEST_VERSION=$(npm show your-package-name version)

          # Update the package.json file in the downstream repository
          echo "{\"version\": \"$LATEST_VERSION\"}" > package.json

          # Commit the changes
          git add package.json
          git commit -m "Update package version to $LATEST_VERSION"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: mavericks_dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
